/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ashwinsinha' at '10/12/16 4:15 PM' with Gradle 2.9
 *
 * @author ashwinsinha, @date 10/12/16 4:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
